import { describe, expect, it } from 'vitest';
import { generateBindings } from '../../src/codegen/generator.js';
import type { AbiSchema } from '../../src/types.js';

const baseAbi: AbiSchema = {
  abi_version: 1,
  circuit: {
    name: 'deposit',
    version: '1.0.0',
    description: 'sample',
    default_k: 10,
    num_public_inputs: 1,
    num_private_witnesses: 3,
  },
  witness: {
    fields: [
      { name: 'collateral', kind: { type: 'u64' }, visibility: 'private' },
      { name: 'collateral_nonce', kind: { type: 'fp' }, visibility: 'private' },
      { name: 'threshold', kind: { type: 'u64' }, visibility: 'private' },
    ],
  },
  public_inputs: {
    fields: [{ name: 'collateral_commitment', kind: { type: 'fp' } }],
  },
  proof: {
    format_version: 1,
    proving_system: 'halo2_ipa',
  },
};

describe('generateBindings', () => {
  it('emits the auto-generated header on the first line', () => {
    const out = generateBindings(baseAbi);
    expect(out.split('\n')[0]).toBe('// auto-generated by @zerostyl/sdk-ts — do not edit');
  });

  it('imports Hex from the SDK package', () => {
    const out = generateBindings(baseAbi);
    expect(out).toContain("import type { Hex } from '@zerostyl/sdk-ts';");
  });

  it('emits a PascalCase Circuit const with metadata', () => {
    const out = generateBindings(baseAbi);
    expect(out).toContain('export const DepositCircuit = {');
    expect(out).toContain('name: "deposit",');
    expect(out).toContain('version: "1.0.0",');
    expect(out).toContain('defaultK: 10,');
    expect(out).toContain('numPublicInputs: 1,');
    expect(out).toContain('numPrivateWitnesses: 3,');
    expect(out).toContain('} as const;');
  });

  it('emits Witness and PublicInputs interfaces with mapped types', () => {
    const out = generateBindings(baseAbi);
    expect(out).toContain('export interface DepositWitness {');
    expect(out).toContain('  collateral: bigint;');
    expect(out).toContain('  collateral_nonce: Hex;');
    expect(out).toContain('  threshold: bigint;');
    expect(out).toContain('export interface DepositPublicInputs {');
    expect(out).toContain('  collateral_commitment: Hex;');
  });

  it('handles multi-segment snake_case circuit names', () => {
    const renamed = { ...baseAbi, circuit: { ...baseAbi.circuit, name: 'private_swap_v2' } };
    const out = generateBindings(renamed);
    expect(out).toContain('export const PrivateSwapV2Circuit = {');
    expect(out).toContain('export interface PrivateSwapV2Witness {');
    expect(out).toContain('export interface PrivateSwapV2PublicInputs {');
  });

  it('emits Record<string, never> for empty field lists', () => {
    const empty: AbiSchema = {
      ...baseAbi,
      circuit: { ...baseAbi.circuit, num_public_inputs: 0, num_private_witnesses: 0 },
      witness: { fields: [] },
      public_inputs: { fields: [] },
    };
    const out = generateBindings(empty);
    expect(out).toContain('export type DepositWitness = Record<string, never>;');
    expect(out).toContain('export type DepositPublicInputs = Record<string, never>;');
  });

  it('handles Merkle-shaped array witnesses', () => {
    const merkle: AbiSchema = {
      ...baseAbi,
      witness: {
        fields: [
          { name: 'leaf', kind: { type: 'fp' }, visibility: 'private' },
          {
            name: 'siblings',
            kind: { type: 'array', kind: { type: 'fp' }, len: 32 },
            visibility: 'private',
          },
          {
            name: 'indices',
            kind: { type: 'array', kind: { type: 'bool' }, len: 32 },
            visibility: 'private',
          },
        ],
      },
    };
    const out = generateBindings(merkle);
    expect(out).toContain('  leaf: Hex;');
    expect(out).toContain('  siblings: ReadonlyArray<Hex>;');
    expect(out).toContain('  indices: ReadonlyArray<boolean>;');
  });

  it('produces output that ends with a trailing newline-separated section', () => {
    const out = generateBindings(baseAbi);
    expect(out.endsWith('\n')).toBe(true);
  });
});
