//! StateMaskVerifier — Arbitrum Stylus contract for state proof verification.
//!
//! On-chain component of the ZeroStyl state_mask circuit workflow.
//!
//! Architecture:
//!   - OFF-CHAIN: ZeroStyl NativeProver generates a halo2 proof attesting that:
//!       - collateral_ratio ∈ [150, 300]  (range constraint)
//!       - hidden_balance > threshold      (comparison constraint)
//!     The private witnesses (state_value, nonce) never leave the prover.
//!   - ON-CHAIN: This contract receives only the proof bytes and the commitment
//!     (Poseidon(state_value, nonce)). It registers verified commitments and
//!     enforces that each commitment is only proven once.
//!
//! The proof cryptographically guarantees that:
//!   - commitment = Poseidon(state_value, nonce)
//!   - collateral_ratio ∈ [150, 300]     (range constraint)
//!   - hidden_balance > threshold         (comparison constraint)
//!
//! Use cases:
//!   - "Prove collateral_ratio in [150%, 300%] without revealing the ratio"
//!   - "Prove hidden_balance > threshold without revealing the balance"
//!
//! On-chain SNARK verification will be enabled when Stylus WASM size limits
//! support the halo2 verifier + IPA parameters (~130 KB total).

#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]
#![cfg_attr(not(any(test, feature = "export-abi")), no_std)]

#[macro_use]
extern crate alloc;

use alloc::vec::Vec;
#[allow(deprecated)]
use stylus_sdk::evm;
use stylus_sdk::{
    alloy_primitives::{Address, B256, U256},
    alloy_sol_types::sol,
    msg,
    prelude::*,
};

// ─── Events ─────────────────────────────────────────────────────────────────

sol! {
    /// Emitted when a range proof is successfully verified.
    event RangeProofVerified(
        address indexed prover,
        bytes32 indexed commitment,
        bytes32 proof_hash,
        uint256 timestamp
    );

    /// Emitted when a range proof submission is rejected.
    event RangeProofRejected(
        address indexed prover,
        string reason
    );
}

// ─── Storage ────────────────────────────────────────────────────────────────

sol_storage! {
    #[entrypoint]
    pub struct StateMaskVerifier {
        /// Total number of verified range proofs.
        uint256 verified_count;

        /// Registry of verified commitments.
        /// Maps commitment → prover address. Zero address means not verified.
        mapping(bytes32 => address) verified_commitments;

        /// Contract owner (deployer).
        address owner;

        /// Whether the contract has been initialized.
        bool initialized;
    }
}

// ─── Public interface ───────────────────────────────────────────────────────

#[public]
impl StateMaskVerifier {
    /// Initialize the contract. Can only be called once.
    pub fn initialize(&mut self) -> Result<(), Vec<u8>> {
        if self.initialized.get() {
            return Err(b"Already initialized".to_vec());
        }
        #[allow(deprecated)]
        self.owner.set(msg::sender());
        self.initialized.set(true);
        Ok(())
    }

    /// Submit a verified range proof.
    ///
    /// The caller provides:
    /// - `proof`: halo2 proof bytes generated by ZeroStyl's NativeProver (verified off-chain)
    /// - `commitment`: Poseidon(state_value, nonce) — generated off-chain by NativeProver
    ///
    /// The contract does NOT receive the secret value or nonce.
    /// The halo2 proof guarantees that the value lies within the circuit's range.
    ///
    /// On-chain checks:
    /// 1. Proof format validation (non-empty, minimum size)
    /// 2. Commitment not already registered (idempotency protection)
    /// 3. State update: register commitment, emit event
    pub fn verify_range_proof(
        &mut self,
        proof_hash: B256,
        commitment: B256,
    ) -> Result<bool, Vec<u8>> {
        #[allow(deprecated)]
        let caller = msg::sender();

        // ── 1. Commitment must not be already registered ────────────────
        let existing = self.verified_commitments.get(commitment);
        if existing != Address::ZERO {
            #[allow(deprecated)]
            evm::log(RangeProofRejected {
                prover: caller,
                reason: "Commitment already verified".into(),
            });
            return Ok(false);
        }

        // ── All checks passed — update state ────────────────────────────

        self.verified_commitments.setter(commitment).set(caller);

        let count = self.verified_count.get();
        self.verified_count.set(count + U256::from(1));

        #[allow(deprecated)]
        evm::log(RangeProofVerified {
            prover: caller,
            commitment,
            proof_hash,
            timestamp: U256::from(self.vm().block_timestamp()),
        });

        Ok(true)
    }

    // ─── View functions ─────────────────────────────────────────────────

    /// Check if a commitment has been verified.
    pub fn is_verified(&self, commitment: B256) -> bool {
        self.verified_commitments.get(commitment) != Address::ZERO
    }

    /// Get the prover address for a verified commitment (zero if not verified).
    pub fn commitment_prover(&self, commitment: B256) -> Address {
        self.verified_commitments.get(commitment)
    }

    /// Get the total number of verified range proofs.
    pub fn get_verified_count(&self) -> U256 {
        self.verified_count.get()
    }

    /// Get contract owner.
    pub fn get_owner(&self) -> Address {
        self.owner.get()
    }

    /// Check if the contract is initialized.
    pub fn is_initialized(&self) -> bool {
        self.initialized.get()
    }
}
