use std::fs;
use std::path::{Path, PathBuf};

use syn::ItemFn;

use crate::codegen::{emit_circuit, emit_descriptor, emit_transformed_contract};
use crate::error::{ExporterError, Result};
use crate::extractor::emit_abi_json;
use crate::parser::parse_fn;
use crate::resolver::resolve_all;

pub const HEADER: &str = "// Auto-generated by zerostyl-export. Do not edit by hand.\n// To regenerate: zerostyl-export transform --contract <source>\n\n";

#[derive(Debug)]
pub struct TransformReport {
    pub circuit_name: String,
    pub circuit_path: PathBuf,
    pub descriptor_path: PathBuf,
    pub contract_transformed_path: PathBuf,
    pub abi_json_path: PathBuf,
}

pub fn transform_contract(
    source_path: &Path,
    circuit_name: Option<&str>,
    output_dir: &Path,
) -> Result<TransformReport> {
    let source = fs::read_to_string(source_path)
        .map_err(|e| ExporterError::Other(format!("reading {}: {e}", source_path.display())))?;

    let item_fn = find_zk_private_fn(&source)?;
    let resolved_name = match circuit_name {
        Some(n) => n.to_string(),
        None => item_fn.sig.ident.to_string(),
    };

    let attrs = parse_fn(&item_fn)?;
    if attrs.is_empty() {
        return Err(ExporterError::Parse(format!(
            "no #[zk_private] param found in fn '{}'",
            item_fn.sig.ident
        )));
    }
    let resolved = resolve_all(&attrs)?;

    let circuit_src = pretty(&emit_circuit(&resolved_name, &resolved)?)?;
    let descriptor_src = pretty(&emit_descriptor(&resolved_name, &resolved)?)?;
    let transformed_src = pretty(&emit_transformed_contract(&item_fn)?)?;
    let abi_json = format!("{}\n", emit_abi_json(&resolved_name, &resolved)?);

    fs::create_dir_all(output_dir)
        .map_err(|e| ExporterError::Other(format!("creating {}: {e}", output_dir.display())))?;

    let circuit_path = output_dir.join("circuit.rs");
    let descriptor_path = output_dir.join("descriptor.rs");
    let contract_transformed_path = output_dir.join("contract_transformed.rs");
    let abi_json_path = output_dir.join("abi.json");

    write_file(&circuit_path, &format!("{HEADER}{circuit_src}"))?;
    write_file(&descriptor_path, &format!("{HEADER}{descriptor_src}"))?;
    write_file(&contract_transformed_path, &format!("{HEADER}{transformed_src}"))?;
    write_file(&abi_json_path, &abi_json)?;

    Ok(TransformReport {
        circuit_name: resolved_name,
        circuit_path,
        descriptor_path,
        contract_transformed_path,
        abi_json_path,
    })
}

fn find_zk_private_fn(source: &str) -> Result<ItemFn> {
    let file: syn::File = syn::parse_str(source)
        .map_err(|e| ExporterError::Parse(format!("source does not parse as Rust: {e}")))?;
    for item in file.items {
        if let syn::Item::Fn(f) = item {
            let has_zk = f.sig.inputs.iter().any(|arg| {
                if let syn::FnArg::Typed(t) = arg {
                    t.attrs.iter().any(|a| a.path().is_ident("zk_private"))
                } else {
                    false
                }
            });
            if has_zk {
                return Ok(f);
            }
        }
    }
    Err(ExporterError::Parse("no fn with #[zk_private] params found in source".into()))
}

fn pretty(src: &str) -> Result<String> {
    let file: syn::File = syn::parse_str(src)
        .map_err(|e| ExporterError::Other(format!("generated code does not parse: {e}")))?;
    Ok(prettyplease::unparse(&file))
}

fn write_file(path: &Path, content: &str) -> Result<()> {
    fs::write(path, content)
        .map_err(|e| ExporterError::Other(format!("writing {}: {e}", path.display())))
}
