// Auto-generated by zerostyl-exporter. Do not edit by hand.
// To regenerate: REGEN_ZK_PRIVATE_DEMO=1 cargo test -p zerostyl-exporter e2e_zk_private_demo_sync

#![allow(clippy::all, dead_code)]
use halo2_proofs::{
    circuit::{Layouter, SimpleFloorPlanner, Value},
    plonk::{Circuit, Column, ConstraintSystem, Error, Instance},
};
use halo2curves::bn256::Fr;
use zerostyl_compiler::gadgets::{
    ComparisonChip, ComparisonConfig, PoseidonCommitmentChip, PoseidonCommitmentConfig,
    RangeProofChip, RangeProofConfig,
};
#[derive(Clone, Debug, Default)]
pub struct DepositCircuit {
    pub collateral: Value<Fr>,
    pub collateral_nonce: Value<Fr>,
    pub threshold: Value<Fr>,
}
#[derive(Debug, Clone)]
pub struct DepositCircuitConfig {
    poseidon_config: PoseidonCommitmentConfig,
    range_config: RangeProofConfig,
    comparison_config: ComparisonConfig,
    instance: Column<Instance>,
}
impl Circuit<Fr> for DepositCircuit {
    type Config = DepositCircuitConfig;
    type FloorPlanner = SimpleFloorPlanner;
    fn without_witnesses(&self) -> Self {
        Self::default()
    }
    fn configure(meta: &mut ConstraintSystem<Fr>) -> Self::Config {
        let poseidon_config = PoseidonCommitmentChip::configure(meta);
        let range_config = RangeProofChip::configure(meta);
        let comparison_config = ComparisonChip::configure(meta);
        let instance = meta.instance_column();
        meta.enable_equality(instance);
        Self::Config { poseidon_config, range_config, comparison_config, instance }
    }
    fn synthesize(
        &self,
        config: Self::Config,
        mut layouter: impl Layouter<Fr>,
    ) -> std::result::Result<(), Error> {
        let poseidon_chip = PoseidonCommitmentChip::construct(config.poseidon_config);
        let range_chip = RangeProofChip::construct(config.range_config);
        let comparison_chip = ComparisonChip::construct(config.comparison_config);
        let collateral_value =
            range_chip.load_value(layouter.namespace(|| "load collateral"), self.collateral)?;
        let collateral_nonce_cell = poseidon_chip.load_private(
            layouter.namespace(|| "load collateral_nonce"),
            self.collateral_nonce,
            1,
        )?;
        let threshold_value =
            comparison_chip.load_value(layouter.namespace(|| "load threshold"), self.threshold)?;
        let collateral_commitment = poseidon_chip.commit(
            layouter.namespace(|| "commit collateral"),
            collateral_value.clone(),
            collateral_nonce_cell,
        )?;
        let collateral_commitment_ref = collateral_commitment.cell();
        layouter.constrain_instance(collateral_commitment_ref, config.instance, 0usize)?;
        range_chip.check_range_bounded(
            layouter.namespace(|| "range check collateral"),
            collateral_value.clone(),
            Fr::from((0) as u64),
            Fr::from(((1000000) as u64) - 1),
            64usize,
        )?;
        range_chip.check_range(
            layouter.namespace(|| "range check collateral (comparison operand)"),
            collateral_value.clone(),
            64usize,
        )?;
        range_chip.check_range(
            layouter.namespace(|| "range check threshold (comparison operand)"),
            threshold_value.clone(),
            64usize,
        )?;
        comparison_chip.assert_gte(
            layouter.namespace(|| "collateral >= threshold"),
            collateral_value.clone(),
            threshold_value.clone(),
            64usize,
        )?;
        Ok(())
    }
}
