// Auto-generated by zerostyl-exporter. Do not edit by hand.
// To regenerate: REGEN_ZK_PRIVATE_DEMO=1 cargo test -p zerostyl-exporter e2e_zk_private_demo_sync

#![allow(clippy::all, dead_code, unused_variables)]
use alloy_primitives::{Bytes, B256};
pub fn deposit(collateral_commitment: B256, threshold: u64, proof: Bytes) -> bool {
    todo!()
}
