import type { AbiSchema, PublicInputField, WitnessField } from '../types.js';
import { fieldTypeToTs } from './type-mapping.js';

const HEADER = '// auto-generated by @zerostyl/sdk-ts — do not edit';

export function generateBindings(abi: AbiSchema): string {
  const name = toPascalCase(abi.circuit.name);
  const sections = [
    HEADER,
    '',
    "import type { Hex } from '@zerostyl/sdk-ts';",
    '',
    emitCircuitConst(name, abi),
    '',
    emitInterface(`${name}Witness`, abi.witness.fields),
    '',
    emitInterface(`${name}PublicInputs`, abi.public_inputs.fields),
    '',
  ];
  return sections.join('\n');
}

function emitCircuitConst(name: string, abi: AbiSchema): string {
  return [
    `export const ${name}Circuit = {`,
    `  name: ${JSON.stringify(abi.circuit.name)},`,
    `  version: ${JSON.stringify(abi.circuit.version)},`,
    `  defaultK: ${abi.circuit.default_k},`,
    `  numPublicInputs: ${abi.circuit.num_public_inputs},`,
    `  numPrivateWitnesses: ${abi.circuit.num_private_witnesses},`,
    '} as const;',
  ].join('\n');
}

function emitInterface(
  name: string,
  fields: ReadonlyArray<WitnessField | PublicInputField>,
): string {
  if (fields.length === 0) {
    return `export type ${name} = Record<string, never>;`;
  }
  const lines = fields.map((f) => `  ${f.name}: ${fieldTypeToTs(f.kind)};`);
  return [`export interface ${name} {`, ...lines, '}'].join('\n');
}

function toPascalCase(s: string): string {
  return s
    .split('_')
    .map((part) => (part.length > 0 ? (part[0]?.toUpperCase() ?? '') + part.slice(1) : ''))
    .join('');
}
