// auto-generated by @zerostyl/sdk-ts — do not edit

import type { Hex } from '@zerostyl/sdk-ts';

export const DepositCircuit = {
  name: "deposit",
  version: "1.0.0",
  defaultK: 10,
  numPublicInputs: 2,
  numPrivateWitnesses: 2,
} as const;

export interface DepositWitness {
  collateral: bigint;
  collateral_nonce: Hex;
  threshold: bigint;
}

export interface DepositPublicInputs {
  collateral_commitment: Hex;
  threshold: bigint;
}
