"""Generate Python bindings from an ABI schema.

The generated module mirrors the TypeScript SDK's output: a circuit-metadata
constant plus frozen dataclasses for the witness and the public inputs.
"""

from __future__ import annotations

import keyword

from ..types import AbiSchema, PublicInputField, WitnessField
from .type_mapping import field_type_to_py

HEADER = "# auto-generated by zerostyl-sdk (python) — do not edit"


def _safe_ident(name: str) -> str:
    """Make an ABI field name a valid, non-keyword Python identifier.

    ABI names are Rust identifiers, so the only collision is a Python keyword
    (e.g. a field literally named ``from``): append an underscore, matching
    PEP 8's convention for keyword-clashing names.
    """
    return f"{name}_" if keyword.iskeyword(name) else name


def generate_bindings(abi: AbiSchema) -> str:
    """Emit a Python module with typed bindings for one circuit."""
    pascal = _pascal_case(abi.circuit.name)
    upper = abi.circuit.name.upper()
    sections = [
        HEADER,
        "",
        "from dataclasses import dataclass",
        "from typing import Final",
        "",
        _emit_circuit_const(upper, abi),
        "",
        _emit_dataclass(f"{pascal}Witness", abi.witness.fields),
        "",
        _emit_dataclass(f"{pascal}PublicInputs", abi.public_inputs.fields),
        "",
    ]
    return "\n".join(sections)


def _emit_circuit_const(upper: str, abi: AbiSchema) -> str:
    c = abi.circuit
    return "\n".join(
        [
            f"{upper}_CIRCUIT: Final = {{",
            f'    "name": {c.name!r},',
            f'    "version": {c.version!r},',
            f'    "default_k": {c.default_k},',
            f'    "num_public_inputs": {c.num_public_inputs},',
            f'    "num_private_witnesses": {c.num_private_witnesses},',
            "}",
        ]
    )


def _emit_dataclass(
    name: str, fields: tuple[WitnessField, ...] | tuple[PublicInputField, ...]
) -> str:
    lines = ["@dataclass(frozen=True)", f"class {name}:"]
    if not fields:
        lines.append("    pass")
    else:
        for f in fields:
            lines.append(f"    {_safe_ident(f.name)}: {field_type_to_py(f.kind)}")
    return "\n".join(lines)


def _pascal_case(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_") if part)
