//! Set `REGEN_ZK_PRIVATE_DEMO=1` to overwrite the committed demo files instead
//! of asserting equality — use after intentional codegen changes.

use std::fs;
use std::path::PathBuf;

use syn::ItemFn;
use zerostyl_exporter::{emit_circuit, emit_descriptor, parser::parse_fn, resolver::resolve_all};

const HEADER: &str = "// Auto-generated by zerostyl-exporter. Do not edit by hand.\n// To regenerate: REGEN_ZK_PRIVATE_DEMO=1 cargo test -p zerostyl-exporter e2e_zk_private_demo_sync\n\n";

fn demo_crate_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../examples/zk_private_demo")
        .canonicalize()
        .expect("demo crate exists")
}

fn pretty(src: &str) -> String {
    let file: syn::File = syn::parse_str(src).expect("emit_* output must parse as a Rust file");
    prettyplease::unparse(&file)
}

#[test]
fn e2e_zk_private_demo_sync() {
    let crate_root = demo_crate_root();
    let source_path = crate_root.join("contract_source.rs");
    let circuit_path = crate_root.join("src/circuit.rs");
    let descriptor_path = crate_root.join("src/descriptor.rs");

    let source = fs::read_to_string(&source_path).expect("contract_source.rs readable");
    let item_fn: ItemFn = extract_fn(&source);

    let attrs = parse_fn(&item_fn).expect("parse_fn succeeds");
    let resolved = resolve_all(&attrs).expect("resolve_all succeeds");

    let circuit_src = pretty(&emit_circuit("deposit", &resolved).expect("emit_circuit"));
    let descriptor_src = pretty(&emit_descriptor("deposit", &resolved).expect("emit_descriptor"));

    let circuit_full = format!("{HEADER}{circuit_src}");
    let descriptor_full = format!("{HEADER}{descriptor_src}");

    if std::env::var("REGEN_ZK_PRIVATE_DEMO").is_ok() {
        fs::write(&circuit_path, &circuit_full).expect("write circuit.rs");
        fs::write(&descriptor_path, &descriptor_full).expect("write descriptor.rs");
        return;
    }

    let on_disk_circuit = fs::read_to_string(&circuit_path).expect("circuit.rs readable");
    let on_disk_descriptor = fs::read_to_string(&descriptor_path).expect("descriptor.rs readable");

    assert_eq!(
        normalize(&on_disk_circuit),
        normalize(&circuit_full),
        "examples/zk_private_demo/src/circuit.rs is out of sync; run `REGEN_ZK_PRIVATE_DEMO=1 cargo test -p zerostyl-exporter e2e_zk_private_demo_sync`"
    );
    assert_eq!(
        normalize(&on_disk_descriptor),
        normalize(&descriptor_full),
        "examples/zk_private_demo/src/descriptor.rs is out of sync; run `REGEN_ZK_PRIVATE_DEMO=1 cargo test -p zerostyl-exporter e2e_zk_private_demo_sync`"
    );
}

fn extract_fn(source: &str) -> ItemFn {
    let file: syn::File = syn::parse_str(source).expect("contract_source.rs parses as a Rust file");
    for item in file.items {
        if let syn::Item::Fn(f) = item {
            return f;
        }
    }
    panic!("no fn found in contract_source.rs");
}

fn normalize(s: &str) -> String {
    s.replace("\r\n", "\n")
}
