use std::fs;
use std::path::PathBuf;

use tempfile::tempdir;
use zerostyl_exporter::{schema::AbiSchema, transform_contract};

fn demo_source() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../examples/zk_private_demo/contract_source.rs")
        .canonicalize()
        .expect("demo source resolves")
}

#[test]
fn transform_contract_writes_four_artifacts_in_output_dir() {
    let dir = tempdir().expect("tempdir");
    let out = dir.path().join("generated");

    let report =
        transform_contract(&demo_source(), None, &out).expect("transform_contract succeeds");

    assert_eq!(report.circuit_name, "deposit");
    assert!(report.circuit_path.exists());
    assert!(report.descriptor_path.exists());
    assert!(report.contract_transformed_path.exists());
    assert!(report.abi_json_path.exists());

    let circuit = fs::read_to_string(&report.circuit_path).unwrap();
    let descriptor = fs::read_to_string(&report.descriptor_path).unwrap();
    let transformed = fs::read_to_string(&report.contract_transformed_path).unwrap();
    let abi = fs::read_to_string(&report.abi_json_path).unwrap();

    assert!(circuit.contains("pub struct DepositCircuit"));
    assert!(circuit.contains("Auto-generated by zerostyl-export"));
    assert!(descriptor.contains("CircuitDescriptor for DepositDescriptor"));
    assert!(descriptor.contains("fn mock_prove"));
    assert!(
        transformed.contains("collateral_commitment : B256")
            || transformed.contains("collateral_commitment: B256")
    );
    assert!(transformed.contains("proof : Bytes") || transformed.contains("proof: Bytes"));

    let parsed: AbiSchema = serde_json::from_str(&abi).expect("abi.json is valid JSON");
    assert_eq!(parsed.circuit.name, "deposit");
    assert_eq!(parsed.public_inputs.fields.len(), 1);
}

#[test]
fn transform_contract_honours_name_override() {
    let dir = tempdir().expect("tempdir");
    let out = dir.path().join("out");

    let report = transform_contract(&demo_source(), Some("private_deposit"), &out)
        .expect("transform_contract succeeds");

    assert_eq!(report.circuit_name, "private_deposit");
    let abi = fs::read_to_string(&report.abi_json_path).unwrap();
    let parsed: AbiSchema = serde_json::from_str(&abi).unwrap();
    assert_eq!(parsed.circuit.name, "private_deposit");
}

#[test]
fn transform_contract_rejects_source_without_zk_private_params() {
    let dir = tempdir().expect("tempdir");
    let src = dir.path().join("plain.rs");
    fs::write(&src, "pub fn plain(x: u64) -> bool { true }").unwrap();

    let err = transform_contract(&src, None, &dir.path().join("out")).unwrap_err();
    assert!(format!("{err}").contains("no fn with #[zk_private] params"));
}

#[test]
fn transform_contract_creates_output_directory_if_missing() {
    let dir = tempdir().expect("tempdir");
    let out = dir.path().join("nested").join("deeper").join("generated");
    assert!(!out.exists());

    transform_contract(&demo_source(), None, &out).expect("transform_contract succeeds");
    assert!(out.is_dir());
}
