# auto-generated by zerostyl-sdk (python) — do not edit

from dataclasses import dataclass
from typing import Final

DEPOSIT_CIRCUIT: Final = {
    "name": 'deposit',
    "version": '1.0.0',
    "default_k": 10,
    "num_public_inputs": 2,
    "num_private_witnesses": 2,
}

@dataclass(frozen=True)
class DepositWitness:
    collateral: int
    collateral_nonce: str
    threshold: int

@dataclass(frozen=True)
class DepositPublicInputs:
    collateral_commitment: str
    threshold: int
